Prefix: .
Status: Reset Mode

Launch Settings:
  Reset Mode: False
  Web Server: False

# Permission Setup
Roles:
  914810543209054238: 
    - is_owner

Users:
  567767732213383198:
    - is_owner

Everyone:
  - is_owner