Prefix: .
Status: Reset Mode

Launch Settings:
  Reset Mode: False
  Web Server: False

# Permission Setup
Roles:
  904959906006851584: 
    - is_owner

Users:
  543041032648917022:
    - is_owner

Everyone:
  - is_member